import './globals.css'
import localFont from "@next/font/local";
const myFont = localFont({src : './fonts/IRAN Sans Regular.woff'})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={myFont.className}>{children}</body>
    </html>
  )
}
